server:
  port: 20002
spring:
  application:
    name: dataAnalyze
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: akokko
    url: jdbc:mysql://1.15.34.154:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&AllowPublicKeyRetrieval=True